development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://fayserver-.herokuapp.com/"
  secret_token: "80ee25ba325472205923d42398e3b39235177e26ec907a07b4322f1a1a7aee06"
  signature_expiration: 3600 # one hour
